{
    'name': 'SaaS Orchestrator',
    'version': '19.0.1.0.1',
    'category': 'Services',
    'summary': """Core engine for SaaS instance lifecycle management via Orquestio API.""",
    'description': """
        Manages SaaS tenants, product blueprints, plans, instances and their
        full lifecycle (provisioning, monitoring, suspension, destruction)
        through integration with the Orquestio orchestrator API.
    """,
    'author': 'Ganemo',
    'maintainer': 'Ganemo',
    'company': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'depends': [
        'base',
        'mail',
        'product',
        'sale_subscription',
        'portal',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/saas_orchestrator_security.xml',
        'views/saas_tenant_views.xml',
        'views/saas_product_blueprint_views.xml',
        'views/saas_product_plan_views.xml',
        'views/saas_instance_views.xml',
        'views/saas_operation_upgrade_wizard_views.xml',
        'views/saas_operation_sprint3_wizard_views.xml',
        'views/saas_instance_custom_domain_wizard_views.xml',
        'views/saas_dashboard_views.xml',
        'views/saas_task_history_views.xml',
        'views/saas_portal_templates.xml',
        'views/product_template_views.xml',
        'views/res_config_settings_views.xml',
        'views/menus.xml',
        'data/mail_templates.xml',
        'data/cron.xml',
        'data/addon_products.xml',
    ],
    'icon': '/saas_orchestrator/static/description/icon.png',
    'images': ['static/description/banner.png'],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': True,
    'currency': 'USD',
    'price': 2000.0,
    'module_type': 'official',
}
