{
    "name": "Kardex PLE 13.1 - Transfer Document Capture",
    "version": "19.0.2.5.0",
    "author": "Ganemo",
    "maintainer": "Ganemo",
    "company": "Ganemo",
    "website": "https://www.ganemo.co",
    'category': 'Accounting',
    "summary": "Capture the real fiscal document (type, series and number) per stock movement for the Peruvian PLE 13.1 (Kardex).",
    "description": """Capture the supporting fiscal document -- type, series and number -- on every stock movement, so the Peruvian PLE 13.1 (Permanent Valued Inventory Ledger / Kardex) reports the real document number from the vendor/customer invoice or the remission guide instead of an internal sequence. Per-movement capture, event-driven population, mass correction for historical records and manual-edit protection.""",
    "depends": [
        'stock',
        'l10n_latam_invoice_document',
        'purchase_stock',
        'sale_stock'
    ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/stock_transfer_document_quickset_views.xml',
        'wizard/stock_transfer_document_range_populate_views.xml',
        'wizard/stock_transfer_document_manage_views.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_views.xml',
    ],
    'demo': [
        'data/demo/invoice_type_document_extension_demo.xml',
    ],
    'application': False,
    "installable": True,
    "auto_install": False,
    "license": "OPL-1",
    "currency": "USD",
    "price": 79.00,
    'module_type': 'official',
    'icon': '/invoice_type_document_extension/static/description/icon.png',
    'images': ['static/description/banner.png'],
}
