{
    'name': 'Absence Manager',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': """Automated attendance monitoring with daily CRON-based absence detection.""",
    'description': """Automatically detect unexcused absences and generate leave records when employees don't check in.
A daily CRON monitors attendance, respects work schedules, rest days (DSO) and public holidays,
and creates traceable absence records linked to your payroll workflow.""",
    'author': 'Ganemo',
    'maintainer': 'Ganemo',
    'company': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'depends': [
        'hr_attendance',
        'hr_holidays_attendance',
        'absence_day',
    ],
    'data': [
        'data/ir_cron_data.xml',
        'views/hr_attendance_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_leave_views.xml',
        'views/hr_leave_type_views.xml',
    ],
    'icon': '/absence_manager/static/description/icon.png',
    'images': ['static/description/banner.png'],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': False,
    'currency': 'USD',
    'price': 49.0,
    'module_type': 'official',
}
