import logging

from odoo import _, api, fields, models

_logger = logging.getLogger(__name__)


class SaleOrder(models.Model):
    """Extensión de sale.order para crear automáticamente ECOs de PLM
    al confirmar una orden de venta con productos a medida sin BOM."""

    _inherit = 'sale.order'

    eco_ids = fields.One2many(
        comodel_name='mrp.eco',
        inverse_name='sale_id',
        string="ECOs",
        help="Engineering Change Orders that were created automatically when "
             "this sale order was confirmed.",
    )
    eco_count = fields.Integer(
        string="ECO Count",
        compute='_compute_eco_count',
        help="Number of Engineering Change Orders generated by this sale "
             "order. Drives the ECOs smart button.",
    )

    @api.depends('eco_ids')
    def _compute_eco_count(self):
        # sudo() para que un usuario de ventas sin permiso de PLM pueda abrir
        # la orden sin que el conteo de ECOs (lectura de mrp.eco) falle.
        for order in self:
            order.eco_count = len(order.sudo().eco_ids)

    def action_view_ecos(self):
        """Abre la vista de ECOs relacionados a esta orden de venta."""
        self.ensure_one()
        action = {
            'type': 'ir.actions.act_window',
            'name': _("Engineering ECOs"),
            'res_model': 'mrp.eco',
            'domain': [('sale_id', '=', self.id)],
            'context': {'default_sale_id': self.id},
        }
        if self.eco_count == 1:
            action.update({
                'view_mode': 'form',
                'res_id': self.eco_ids.id,
            })
        else:
            action['view_mode'] = 'list,form'
        return action

    def action_confirm(self):
        """Extiende la confirmación estándar de la orden de venta.
        Después de confirmar, evalúa cada línea de venta y crea un ECO
        (mrp.eco) por cada producto que cumpla las condiciones de
        elegibilidad.
        """
        # Ejecutar la confirmación estándar primero.
        res = super().action_confirm()

        # Procesar cada orden en el recordset (pueden confirmarse varias a la vez).
        for order in self:
            order._create_plm_ecos_for_custom_products()

        return res

    def _create_plm_ecos_for_custom_products(self):
        """Evalúa las líneas de la orden y crea ECOs para productos elegibles.

        Un producto es elegible si cumple TODAS las condiciones:
        1. Su categoría tiene requires_engineering = True
        2. No tiene ninguna BOM activa (ni por template ni por variante)
        3. Es un bien almacenable (type='consu' y is_storable=True)

        Idempotencia:
        - Antes de crear, verifica que no exista ya una BOM para el producto
        - Verifica que no exista ya un ECO generado por esta orden para el
          mismo producto
        """
        self.ensure_one()

        # Recopilar los product.template únicos elegibles de las líneas.
        eligible_templates = self._get_eligible_product_templates()
        if not eligible_templates:
            return

        # Crear un ECO (con BOM) por cada product.template elegible.
        # Se usa sudo() porque el usuario que confirma la venta puede no tener
        # permisos de PLM (mrp.eco / mrp.bom). La creación del ECO debe ocurrir
        # igual; los privilegios se elevan solo para estas operaciones técnicas,
        # no para la confirmación de la venta en sí.
        EcoModel = self.env['mrp.eco'].sudo()
        BomModel = self.env['mrp.bom'].sudo()
        StageModel = self.env['mrp.eco.stage'].sudo()
        for tmpl in eligible_templates:
            eco_type = tmpl.categ_id.eco_type_id
            if not eco_type:
                _logger.error(
                    "La categoría '%s' tiene 'Requiere ingeniería a medida' "
                    "activo pero no tiene un Tipo de ECO configurado. "
                    "No se puede crear ECO para producto '%s'. Orden: %s",
                    tmpl.categ_id.name, tmpl.name, self.name,
                )
                continue
            try:
                # Obtener el primer stage (por sequence) del eco_type.
                first_stage = StageModel.search(
                    [('type_ids', 'in', eco_type.id)], limit=1,
                )
                # Crear primero la BOM vacía para el producto.
                # Ingeniería la completará con sus componentes desde el ECO.
                bom = BomModel.create({
                    'product_tmpl_id': tmpl.id,
                    'product_qty': 1.0,
                })
                # Crear el ECO vinculado a la BOM y a la orden de venta.
                eco_vals = {
                    'name': "%s: %s" % (self.name, tmpl.name),
                    'type': 'bom',
                    'type_id': eco_type.id,
                    'product_tmpl_id': tmpl.id,
                    'bom_id': bom.id,
                    'sale_id': self.id,
                }
                if first_stage:
                    eco_vals['stage_id'] = first_stage.id
                EcoModel.create(eco_vals)
                _logger.info(
                    "ECO de PLM y BOM creados para producto '%s' "
                    "(template ID %s) desde la orden de venta '%s'.",
                    tmpl.name, tmpl.id, self.name,
                )
            except Exception:
                # Registrar el error sin romper la confirmación de la venta.
                _logger.exception(
                    "Error al crear ECO/BOM de PLM para producto '%s' "
                    "(template ID %s) desde la orden '%s'. "
                    "La confirmación de la venta continúa.",
                    tmpl.name, tmpl.id, self.name,
                )

    def _get_eligible_product_templates(self):
        """Retorna los product.template únicos elegibles de las líneas de venta.

        Filtra por las tres condiciones de elegibilidad y aplica las
        verificaciones de idempotencia.
        """
        self.ensure_one()
        templates = self.env['product.template']

        # Recopilar templates únicos que cumplan condiciones básicas.
        candidate_templates = self.env['product.template']
        for line in self.order_line:
            product = line.product_id
            if not product:
                continue
            tmpl = product.product_tmpl_id

            # Condición 1: la categoría requiere ingeniería.
            if not tmpl.categ_id.requires_engineering:
                continue

            # Condición 3: debe ser un bien almacenable.
            # En Odoo 19: type='consu' + is_storable=True.
            if tmpl.type != 'consu' or not tmpl.is_storable:
                continue

            candidate_templates |= tmpl

        if not candidate_templates:
            return templates

        # Condición 2 + Idempotencia: excluir templates que ya tengan BOM.
        # sudo() porque el usuario que confirma la venta puede no tener permiso
        # de lectura sobre mrp.bom / mrp.eco (modelos de PLM).
        existing_boms = self.env['mrp.bom'].sudo().search([
            ('product_tmpl_id', 'in', candidate_templates.ids),
        ])
        templates_with_bom = existing_boms.mapped('product_tmpl_id')

        # También verificar BOMs asociadas a variantes específicas de estos templates.
        product_ids = self.order_line.mapped('product_id').filtered(
            lambda p: p.product_tmpl_id in candidate_templates
        ).ids
        if product_ids:
            variant_boms = self.env['mrp.bom'].sudo().search([
                ('product_id', 'in', product_ids),
            ])
            templates_with_bom |= variant_boms.mapped('product_tmpl_id')

        # Idempotencia: excluir templates que ya tengan un ECO creado
        # por esta misma orden de venta (usa sale_id Many2one).
        existing_ecos = self.env['mrp.eco'].sudo().search([
            ('sale_id', '=', self.id),
            ('product_tmpl_id', 'in', candidate_templates.ids),
        ])
        templates_with_eco = existing_ecos.mapped('product_tmpl_id')

        # Templates finales = candidatos - con BOM - con ECO existente.
        templates = candidate_templates - templates_with_bom - templates_with_eco
        return templates
