import math
from datetime import datetime

import pytz
from dateutil.relativedelta import relativedelta

from odoo import api, fields, models
from odoo.exceptions import ValidationError


def _convert_date_timezone_to_utc(user, date_order, format_time='%Y-%m-%d %H:%M:%S'):
    tz = pytz.timezone(user.tz) if user.tz else pytz.utc
    date_order = datetime.strptime(date_order, format_time)
    datetime_with_tz = tz.localize(date_order, is_dst=None)
    date_order = datetime_with_tz.astimezone(pytz.utc)
    date_order = datetime.strftime(date_order, format_time)
    return date_order


class HolidayPetitionWizard(models.TransientModel):
    _name = 'holiday.petition.wizard'
    _description = 'Vacation Request and Compensation'

    nro_holidays = fields.Float(
        string='Number of Vacation Days',
        required=True,
        help='Total number of vacation days to request or compensate. '
             'The system will distribute these days across the available allocations with pending balance, '
             'starting from the oldest allocation. Must be greater than zero.'
    )
    employee_id = fields.Many2one(
        comodel_name='hr.employee',
        string='Employee',
        required=True,
        help='The employee for whom the vacation request or compensation is being processed. '
             'Only allocations belonging to this employee will be considered.'
    )
    from_date = fields.Date(
        string='From',
        required=True,
        help='Start date of the vacation or compensation period. '
             'The end date is automatically calculated based on the number of days requested.'
    )
    to_date = fields.Date(
        string='To',
        compute='_compute_to_date',
        store=True,
        help='End date of the vacation period. Automatically computed from "From" date plus the number of days requested. '
             'This field is read-only.'
    )
    holiday_status_id = fields.Many2one(
        comodel_name='hr.leave.type',
        string='Time Off Type',
        required=True,
        default=lambda self: self.env.ref('holiday_process.hr_leave_type_23'),
        help='The type of leave used for this request. Defaults to "Descanso Vacacional". '
             'Only allocations matching this leave type with a pending balance will be displayed.'
    )
    is_generated = fields.Boolean(
        string='Was Generated?',
        help='Internal flag set to True after the absence records have been created from this wizard. '
             'Controls the visibility of the confirmation buttons.'
    )
    allocation_ids = fields.Many2many(
        comodel_name='hr.leave.allocation',
        string='Allocations',
        compute='_compute_allocation_ids',
        help='Read-only list of allocations available for the selected employee and leave type that still have pending days. '
             'Days are consumed from these allocations in chronological order when generating the absence.'
    )
    msj = fields.Char(
        string='Message',
        readonly=True,
        help='Informational message displayed when the total pending days across all allocations '
             'is insufficient to cover the requested number of days.'
    )
    absence_ids = fields.Many2many(
        comodel_name='hr.leave',
        string='Absences',
        help='List of absence records generated by this wizard. '
             'Each record represents a portion of the requested vacation days linked to a specific allocation.'
    )
    is_settlement = fields.Boolean(
        string='Is Settlement?',
        help='When enabled, indicates that this process is a final settlement (liquidation) of vacation days. '
             'In settlement mode, the absence is marked as paid but not physically taken by the employee.'
    )
    time_from = fields.Datetime(
        string='Date From (Native)',
        help='Internal field storing the UTC start datetime used when creating or updating the native hr.leave record. '
             'Automatically computed from the "From" date adjusted to the user\'s timezone.'
    )
    time_to = fields.Datetime(
        string='Date To (Native)',
        help='Internal field storing the UTC end datetime used when creating or updating the native hr.leave record. '
             'Automatically computed from the calculated "To" date adjusted to the user\'s timezone.'
    )

    @api.depends('employee_id', 'holiday_status_id')
    def _compute_allocation_ids(self):
        for rec in self:
            if rec.employee_id and rec.holiday_status_id:
                allocation_ids = self.env['hr.leave.allocation'].search([
                    ('employee_id', '=', rec.employee_id.id),
                    ('holiday_status_id', '=', rec.holiday_status_id.id),
                    ('pending_holiday', '>', 0)
                ])
                rec.allocation_ids = allocation_ids
            else:
                rec.allocation_ids = False

    @api.depends('nro_holidays', 'from_date')
    def _compute_to_date(self):
        for rec in self:
            if rec.nro_holidays and rec.from_date:
                rec.to_date = rec.from_date + relativedelta(days=math.ceil(rec.nro_holidays) - 1)

    @api.constrains('from_date', 'to_date')
    def _check_dates(self):
        for rec in self:
            if rec.from_date and rec.to_date:
                if rec.from_date > rec.to_date:
                    raise ValidationError('La fecha "Desde" no puede ser mayor que la fecha "Hasta".')

    def action_generate_holidays(self):
        if self.nro_holidays <= 0:
            raise ValidationError('El número de días de vacaciones no pueden ser menor o igual a 0.')
        hr_allocation_ids = self.allocation_ids
        nro = self.nro_holidays
        total_pending_holiday = sum(line.pending_holiday for line in hr_allocation_ids)
        context = {
            'default_is_generated': True,
            'default_employee_id': self.employee_id.id,
            'default_from_date': self.from_date,
            'default_to_date': self.to_date,
            'default_holiday_status_id': self.holiday_status_id.id,
        }

        if total_pending_holiday < nro:
            context.update({
                'default_msj': 'La sumatoria total de días pendientes de las asignaciones "{}"'
                               ' es menor que la cantidad de días a asignar "{}".'.format(total_pending_holiday, nro)
            })
        else:
            absences = []
            request_date_from = self.from_date
            for allocation in hr_allocation_ids.sorted(key=lambda r: r.from_date):
                if nro > 0:
                    days = allocation.pending_holiday if nro >= allocation.pending_holiday else nro
                    absence_id = self.create_holiday_absences(request_date_from, days, allocation)
                    absences.append(absence_id.id)
                    if not self._context.get('settlement'):
                        request_date_from += relativedelta(days=days)
                    nro -= days
                    if nro <= 0 and self._context.get('settlement'):
                        allocation.date_to = absence_id.date_to
                        break

            context.update({
                'default_absence_ids': absences,
            })
        return self.action_reopen_wizard(context=context)

    def action_reopen_wizard(self, context=None):
        if self._context.get('settlement'):
            form = self.env.ref('holiday_process.holiday_settlement_wizard_view_form')
            name = 'Compensación de vacaciones'
        else:
            form = self.env.ref('holiday_process.holiday_petition_wizard_view_form')
            name = 'Solicitud de vacaciones'

        if context:
            if context.get('active_id'):
                keys_to_delete = ['default_absence_ids', 'default_allocation_ids', 'active_id', 'active_ids', 'default_is_generated']
                for key in keys_to_delete:
                    context.pop(key, None)
                    
        return {
            'name': name,
            'res_model': self._name,
            'view_mode': 'form',
            'views': [(form.id, 'form')],
            'context': context,
            'view_id': form.id,
            'type': 'ir.actions.act_window',
            'target': 'new'
        }

    def create_holiday_absences(self, from_date, total_days, allocation_id):
        to_date = from_date + relativedelta(days=total_days) - relativedelta(days=1)
        self.time_to = _convert_date_timezone_to_utc(self.env.user, '{} 08:00:00'.format(from_date))
        self.time_from = _convert_date_timezone_to_utc(self.env.user, '{} 17:00:00'.format(to_date))
        domain = [
            ('date_from', '<', self.time_from),
            ('date_to', '>', self.time_to),
            ('employee_id', '=', self.employee_id.id),
        ]
        absence_id = self.env['hr.leave'].search(domain)
        if absence_id:
            absence_id.update({
                'holiday_status_id': self.holiday_status_id.id,
                'employee_id': self.employee_id.id,
                'hr_leave_id': allocation_id.id, 'request_date_to': to_date,
                'request_date_from': from_date,
                'date_from': _convert_date_timezone_to_utc(self.env.user, '{} 08:00:00'.format(from_date)),
                'date_to': _convert_date_timezone_to_utc(self.env.user, '{} 17:00:00'.format(to_date))
            })
        else:
            absence_id = self.env['hr.leave'].create({
                'holiday_status_id': self.holiday_status_id.id,
                'employee_id': self.employee_id.id,
                'hr_leave_id': allocation_id.id, 'request_date_to': to_date,
                'request_date_from': from_date,
                # los minutos no son cero porque cuando es la misma fecha, no se calcula un día
                'date_from': _convert_date_timezone_to_utc(self.env.user, '{} 08:00:00'.format(from_date)),
                'date_to': _convert_date_timezone_to_utc(self.env.user, '{} 17:00:00'.format(to_date))
            })
        if self._context.get('settlement'):
            absence_id.name = """Esta ausencia no ha sido gozada, sino que se ha creado para dejar constancia 
            que ya se han pagado por medio de una compra o liquidación."""
            self.env['hr.leave'].search([('id', '=', absence_id.id)]).write({
                'number_of_days': total_days
            })
        return absence_id
