# Part of Ganemo. See LICENSE file for full copyright and licensing details.

from odoo.tests import TransactionCase, tagged


@tagged("post_install", "-at_install")
class TestAutoCreateProject(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.partner = cls.env["res.partner"].create({"name": "Auto Project Customer"})
        cls.team_on = cls.env["crm.team"].create(
            {"name": "Project Team", "auto_create_project": True}
        )
        cls.team_off = cls.env["crm.team"].create(
            {"name": "Plain Team", "auto_create_project": False}
        )
        # A sellable service product that does NOT trigger the native flow.
        cls.service_plain = cls.env["product.product"].create(
            {
                "name": "Consulting (no native project)",
                "type": "service",
                "service_tracking": "no",
                "list_price": 100.0,
            }
        )
        # A service product configured to make Odoo generate a project natively.
        cls.service_native = cls.env["product.product"].create(
            {
                "name": "Service that creates a project",
                "type": "service",
                "service_tracking": "project_only",
                "list_price": 100.0,
            }
        )

    def _new_order(self, team, product):
        return self.env["sale.order"].create(
            {
                "partner_id": self.partner.id,
                "team_id": team.id,
                "order_line": [(0, 0, {"product_id": product.id})],
            }
        )

    def test_default_from_team(self):
        """The order boolean inherits the sales team policy."""
        self.assertTrue(self._new_order(self.team_on, self.service_plain).auto_create_project)
        self.assertFalse(self._new_order(self.team_off, self.service_plain).auto_create_project)

    def test_creates_project_without_native_product(self):
        """Confirming a flagged order creates a project + analytic account,
        with no service product configured to generate one."""
        order = self._new_order(self.team_on, self.service_plain)
        self.assertFalse(order.project_id)
        order.action_confirm()
        self.assertTrue(order.project_id, "A project should have been created")
        self.assertTrue(order.project_id.account_id, "The project must carry an analytic account")
        self.assertEqual(order.project_id.reinvoiced_sale_order_id, order)
        self.assertTrue(order.project_id.allow_billable)
        # The analytic account propagates to the order line distribution.
        account_id = order.project_id.account_id.id
        line = order.order_line[0]
        self.assertTrue(
            any(str(account_id) in key.split(",") for key in (line.analytic_distribution or {})),
            "The project's analytic account should reach the order line distribution",
        )

    def test_no_project_when_flag_off(self):
        """Per-order override wins over the team default."""
        order = self._new_order(self.team_on, self.service_plain)
        order.auto_create_project = False
        order.action_confirm()
        self.assertFalse(order.project_id)

    def test_does_not_duplicate_native_project(self):
        """When a service product already makes Odoo create a project, this
        module stays out of the way: exactly one project, the native one."""
        order = self._new_order(self.team_on, self.service_native)
        order.action_confirm()
        self.assertTrue(order.project_id)
        # The native project is the one generated by the service line.
        self.assertEqual(order.order_line[0].project_id, order.project_id)
        self.assertEqual(len(order.project_ids), 1, "No duplicate project must be created")

    def test_idempotent_on_reconfirmation(self):
        """Cancel -> draft -> confirm must not create a second project."""
        order = self._new_order(self.team_on, self.service_plain)
        order.action_confirm()
        project = order.project_id
        self.assertTrue(project)
        order._action_cancel()
        order.action_draft()
        order.action_confirm()
        self.assertEqual(order.project_id, project, "Re-confirmation must reuse the project")
