from odoo import models
from odoo.http import request
import re
import werkzeug.wrappers


# Matches /appointment or /{lang}/appointment (e.g. /en/appointment, /es/appointment,
# /pt_BR/appointment, /zh-hans/appointment). The language segment is 2-5 chars
# optionally followed by _XX or -xx (e.g. pt_BR, zh-hans).
_APPOINTMENT_PATH_RE = re.compile(
    r'^(/[a-z]{2,5}(?:[_-][a-zA-Z]{2,4})?)?/appointment(?:/|$)',
    re.IGNORECASE,
)


class IrHttp(models.AbstractModel):
    """Override ir.http to block appointment crawler traps and add SEO headers.

    Implements two protection layers:
    - Layer 1: Returns HTTP 404 immediately for appointment URLs with ?domain=
      containing datetime patterns. These are pager trap URLs generated by the
      appointment module — they change on every request, creating an infinite
      crawl loop that exhausts server memory (signal 9, worker killed).
    - Layer 2: Adds X-Robots-Tag: noindex, nofollow to HTML responses for
      appointment URLs with ?date= or ?datetime= parameters. These are
      calendar day links — legitimate but should not be indexed.

    Both layers support Odoo multilingual URL prefixes (/en/, /es/, /fr/, etc.).
    """

    _inherit = 'ir.http'

    @classmethod
    def _is_appointment_path(cls, path):
        """Return True if path is an appointment page (with or without lang prefix).

        Examples that match:
            /appointment
            /appointment/page/3
            /en/appointment
            /en/appointment/page/4
            /es/appointment
            /pt_BR/appointment/page/2
        """
        return bool(_APPOINTMENT_PATH_RE.match(path))

    @classmethod
    def _is_appointment_crawler_trap(cls):
        """Detect appointment pagination trap URLs before processing them.

        Trap pattern:
            /[lang/]appointment[/page/N]?domain=...datetime.datetime(...)...

        The domain parameter always contains a fresh datetime.datetime() call
        with microsecond precision (e.g. datetime.datetime(2026,3,13,5,54,26,604179)).
        Each visit produces a unique URL — crawlers follow every link, generating
        thousands of unique requests that eventually kill Odoo workers via OOM.

        Detection:
            - Path matches _APPOINTMENT_PATH_RE  (covers /en/, /es/, etc.)
            - Query string has at least one 'domain=' parameter
            - Query string contains 'datetime'  (the Python class name) OR
              '%3a' (URL-encoded colon, present in timestamp strings like 05:54:26)
        """
        path = request.httprequest.path
        if not cls._is_appointment_path(path):
            return False
        qs = request.httprequest.query_string.decode('utf-8', errors='ignore').lower()
        return 'domain=' in qs and ('datetime' in qs or '%3a' in qs)

    @classmethod
    def _dispatch(cls, endpoint):
        # --- Layer 1: Block crawler trap before any processing ---
        if cls._is_appointment_crawler_trap():
            response = werkzeug.wrappers.Response(status=404)
            response.headers['X-Robots-Tag'] = 'noindex'
            return response

        response = super()._dispatch(endpoint)

        # --- Layer 2: Add noindex header for calendar date params ---
        # These URLs are valid (not traps) but should not be indexed.
        # Appointment ?date= links are generated dynamically by JS; we
        # cannot remove them server-side, so we tell bots to ignore them.
        # Only process actual HTTP responses — JSON-RPC endpoints return a plain
        # dict which has no .headers attribute and needs no robot directives.
        path = request.httprequest.path
        if isinstance(response, werkzeug.wrappers.Response) and cls._is_appointment_path(path):
            qs = request.httprequest.query_string.decode('utf-8', errors='ignore').lower()
            content_type = response.headers.get('Content-Type', '')
            if 'text/html' in content_type and ('date=' in qs or 'datetime=' in qs):
                response.headers['X-Robots-Tag'] = 'noindex, nofollow'

        return response

