{
    'name': 'Stock Delivery Payment Control',
    'version': '19.0.1.0.0',
    'category': 'Inventory/Delivery',
    'summary': 'Control delivery validation based on payment status',
    'icon': '/stock_delivery_payment_control/static/description/icon.png',
    'author': 'Ganemo',
    'maintainer': 'Ganemo',
    'company': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'license': 'OPL-1',
    'depends': ['sale_management', 'stock'],
    'images': ['static/description/banner.png'],
    'currency': 'USD',
    'price': 97.0,
    'module_type': 'official',
    'data': [
        # 'security/ir.model.access.csv',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_picking_type_views.xml',
        'views/res_partner_views.xml',
        'views/crm_team_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
