from odoo import models, fields, api, _
import uuid

class ProjectProject(models.Model):
    _name = 'project.project'
    _inherit = ['project.project', 'portal.mixin']
    
    evidence_report_url = fields.Char(
        string='Evidence Report URL', 
        compute='_compute_evidence_report_url',
        help="Public link to share the Project Evidence report."
    )
    
    evidence_final_stage_id = fields.Many2one(
        'project.task.type', 
        string='Final Evidence Stage',
        domain="[('user_id', '=', False)]", # Simple domain, usually stages are shared or project specific
        help="Stage to move tasks to when evidence is completed from the portal."
    )
    
    evidence_final_state = fields.Selection(
        [
            ('01_in_progress', 'In Progress'),
            ('1_done', 'Done'),
            ('03_approved', 'Approved'),
            ('1_canceled', 'Canceled'),
            ('04_waiting_normal', 'Waiting'),
        ],
        string='Final Evidence State',
        default='1_done',
        help="State to set on tasks when evidence is completed from the portal."
    )
    
    force_min_photos = fields.Boolean(
        string='Force Min Photos',
        default=True,
        help="If checked, tasks cannot be marked as Done in the portal unless all minimum photo requirements are met."
    )

    @api.depends('access_token')
    def _compute_evidence_report_url(self):
        base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        for project in self:
            if project.access_token:
                project.evidence_report_url = f"{base_url}/project/evidence/{project.id}?access_token={project.access_token}"
            else:
                project.evidence_report_url = False

    def action_generate_evidence_token(self):
        for project in self:
            if not project.access_token:
                project.access_token = self.env['ir.config_parameter'].sudo()._get_param('database.uuid')
                project._portal_ensure_token()
        return True

    def action_revoke_evidence_token(self):
        self.access_token = False
        return True

    def action_preview_evidence_report(self):
        self.ensure_one()
        
        # Invalidate cache to ensure we see any token generated by other users/tabs
        self.invalidate_recordset(['access_token'])
        
        # Get existing token or generate a new one locally
        token = self.access_token
        if not token:
            token = str(uuid.uuid4())
            self.sudo().write({'access_token': token})
            # Commit needed to ensure the token is visible to the public controller immediately
            if not self.env.context.get('test_mode'): 
                self.env.cr.commit()
        
        # Explicitly construct URL using the local 'token' variable
        # This guarantees it is never empty in the URL, eliminating the race condition
        base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        url = f"{base_url}/project/evidence/{self.id}?access_token={token}"
        
        return {
            'type': 'ir.actions.act_url',
            'url': url,
            'target': 'new',
        }

    def action_view_internal_evidence(self):
        self.ensure_one()
        return self.env.ref('project_task_photo_evidence.action_report_project_evidence').report_action(self)

    # --- Website Report Public Access ---
    website_access_token = fields.Char('Website Access Token', copy=False)
    
    website_report_url = fields.Char(
        string='Website Report URL', 
        compute='_compute_website_report_url',
        help="Public link to share the modern Website Evidence report."
    )

    @api.depends('website_access_token')
    def _compute_website_report_url(self):
        base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        for project in self:
            if project.website_access_token:
                project.website_report_url = f"{base_url}/project/website/evidence/project/{project.id}?access_token={project.website_access_token}"
            else:
                project.website_report_url = False

    def action_generate_website_token(self):
        for project in self:
            if not project.website_access_token:
                project.website_access_token = str(uuid.uuid4())
        return True

    def action_revoke_website_token(self):
        self.sudo().write({'website_access_token': False})
        return True
