{
    'name': 'Payroll Fields',
    'version': '19.0.1.0.1',
    'category': 'Human Resources/Payroll',
    'summary': """Adds payroll month field to payslips and creates analysis views for inputs, worked days, and payslip lines.""",
    'description': """This module adds a computed Payroll Month (date_start_dt) field to payslips, automatically determining which month each payslip corresponds to based on its date range. It also creates dedicated analysis menu items and list/pivot/graph views for Entry Analysis (Payslip Inputs), Worked Days Analysis, and Payroll Analysis (Payslip Lines), enabling better control of payroll data import and reporting.""",
    'author': 'Ganemo',
    'maintainer': 'Ganemo',
    'company': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'depends': [
        'hr_payroll',
        'hr_work_entry_enterprise',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/hr_rules.xml',
        'data/hr_salary_rule_report_category_data.xml',
        'views/hr_salary_rule_report_category_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_payslip_input_views.xml',
        'views/hr_payslip_line_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_payslip_worked_days_views.xml',
        'views/hr_payslip_input_menus.xml',
        'views/hr_payslip_worked_days_menus.xml',
        'views/hr_payslip_line_menus.xml',
        'views/hr_payroll_hide_menus.xml',
        'views/hr_payslip_run_views.xml',
    ],
    'icon': '/payroll_field/static/description/icon.png',
    'images': ['static/description/banner.png'],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'payroll_field/static/src/**/*',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': False,
    'currency': 'USD',
    'price': 357.00,
    'module_type': 'official',
}
