{
    'name': 'Third parties delivery',
    'version': '19.0.1.0.1',
    'author': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'summary': 'Adds to the delivery guide a field for third-party delivery address.',
    'description':'Add an additional field to indicate a delivery address to third parties in the delivery guide (Warehouse exit note).',
    'depends': ['l10n_pe_edi_stock'],
    'data': ['views/stock_picking_views.xml'],
    'installable': True,
    'auto_install': False,
    'application': False,
    'module_type':'official',
    'license': 'OPL-1',
    'currency': 'USD',
    'price': 10.00,
    'icon': '/third_parties_delivery/static/description/icon.png',
    'images': ['static/description/banner.png'],
}
