{
    'name': 'Automatic Leave Type',
    'version': '19.0.1.0.0',
    'category': 'Human Resources/Payroll',
    'summary': """Pre-load all 25 official Peruvian absence types from the Planilla Electrónica (PLAME) into Odoo.""",
    'description': """Automatically imports the complete catalog of Peruvian absence types defined by the Planilla Electrónica (T-Registro / PLAME). Creates 25 Work Entry Types and 25 Leave Types, classified as Suspensión Perfecta (unpaid) and Suspensión Imperfecta (paid), with subsidy flags for EsSalud payroll rules. Zero manual configuration required.""",
    'author': 'Ganemo',
    'maintainer': 'Ganemo',
    'company': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'depends': [
        'hr_payroll',
        'hr_work_entry_holidays',
        'absence_day',
    ],
    'data': [
        'data/hr_work_entry_type_data.xml',
        'data/hr_leave_type_data.xml',
        'views/hr_work_entry_type_views.xml',
    ],
    'icon': '/automatic_leave_type/static/description/icon.png',
    'images': ['static/description/banner.png'],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': False,
    'currency': 'USD',
    'price': 20.0,
    'module_type': 'official',
}
